[package]
name = "walmart_partner_api"
version = "0.1.1"
authors = ["Flux Xu <fluxxu@gmail.com>"]
description = "Rust client for Walmart Partner APIs"
repository = "https://github.com/Ventmere/walmart-partner-api"
license = "MIT"
exclude = ["target"]

[dependencies]
reqwest = "0.7.2"
error-chain = "0.10.0"
base64 = "0.6.0"
chrono = { version = "0.4", features = ["serde"] }
openssl = "0.9.15"
serde = "1.0.11"
serde_json = "1.0.2"
serde_derive = "1.0.11"
rand = "0.3.16"
serde_urlencoded = "0.5.1"
multipart = { version = "0.13.1" }